# Dataset Comparison Tool Configuration
# This file controls all aspects of the comparison pipeline

## Data source configuration
data_sources:
  dataset_1:
    folder: "Feb2025"
    period_name: "feb"
  dataset_2:
    folder: "July2025"
    period_name: "july"

# Database configuration
database:
  path: "hcr_comparison.db"
  
# Schema configuration
schema:
  schema_folder: "schema"
  default_schema: "hcr_default"
  schema_mapping:
    highly_cited_only: "hcr_default"
    incites_researchers: "hcr_default"
  
# Sheets to process from Excel files
sheets_to_process:
  - "Highly Cited only"
  - "Incites Researchers"

# NEW: Light Transform Configuration Section
light_transform:
  # Column mapping configuration (moved from root level)
  column_mapping:
    name: "Name"
    percent_docs_cited: "% Docs Cited"
    web_of_science_documents: "Web of Science Documents"
    rank: "Rank"
    times_cited: "Times Cited"
    affiliation: "Affiliation"
    web_of_science_researcherid: "Web of Science ResearcherID"
    category_normalised_citation_impact: "Category Normalized Citation Impact"
    orcid: "ORCID"
    highly_cited_papers: "Highly Cited Papers"
    hot_papers: "Hot Papers"
    esi_field: "ESI Field"
    indicative_cross_field_score: "Indicative Cross-Field Score"
  
  # ESI field normalisation configuration
  esi_normalisation:
    enabled: true
    canonical_mappings:
      'agricultural sciences': 'Agricultural Sciences'
      'biology_biochemistry': 'Biology Biochemistry'
      'chemistry': 'Chemistry'
      'clinical medicine': 'Clinical Medicine'
      'computer science': 'Computer Science'
      'economics and business': 'Economics and Business'
      'engineering': 'Engineering'
      'environment_ecology': 'Environment Ecology'
      'geosciences': 'GeoSciences'
      'immunology': 'Immunology'
      'materials science': 'Materials Science'
      'microbiology': 'Microbiology'
      'molecular biology and genetics': 'Molecular Biology and Genetics'
      'neuroscience and behaviour': 'Neuroscience and Behaviour'
      'pharmacology and toxicology': 'Pharmacology and Toxicology'
      'physics': 'Physics'
      'plant and animal science': 'Plant and Animal Science'
      'psychiatry_psychology': 'Psychiatry Psychology'
      'social sciences': 'Social Sciences'
      'space science': 'Space Science'
    
    # Options for handling unknown ESI fields
    unknown_field_strategy: "keep_original"  # "keep_original", "flag_error", "use_default"
    default_field: "Unknown"
  
  # Duplicate removal configuration (moved from data_cleaning)
  duplicate_removal:
    enabled: true
    duplicate_check_columns:
      - "name"
      - "esi_field"
    strategy: "keep_first"  # "keep_first", "keep_last", "flag_all"
    case_sensitive_matching: false
    
  # NULL value handling configuration
  null_handling:
    strategy: "fail"  # "fail", "skip", "default", "interpolate"
    
    # Default values to use when strategy is "default"
    default_values:
      percent_docs_cited: 0.0
      web_of_science_documents: 0
      rank: 0
      times_cited: 0
      affiliation: "Unknown"
      web_of_science_researcherid: ""
      category_normalised_citation_impact: 0.0
      orcid: ""
      highly_cited_papers: 0
      hot_papers: 0
      indicative_cross_field_score: 0.0
    
    # Critical fields that should never be NULL (regardless of strategy)
    critical_fields_never_null:
      - "name"
      - "esi_field"
  
  # Validation configuration
  validation:
    enabled: true
    fail_on_validation_error: true
    
    # Validation checks to perform
    checks:
      - "check_required_columns"
      - "check_data_types" 
      - "check_value_ranges"
      - "check_null_constraints"
      - "check_duplicate_constraints"
    
    # Performance validation
    max_processing_time_seconds: 30
    max_memory_usage_mb: 500

# Critical columns required for pipeline to run (references light_transform.column_mapping keys)
critical_columns:
  - "name"
  - "times_cited"
  - "highly_cited_papers"
  - "hot_papers"
  - "indicative_cross_field_score"
  - "esi_field"

# Validation rules for data quality checking (references light_transform.column_mapping keys)
validation_rules:
  times_cited:
    min: 50
    max: 100000
    required: true
  highly_cited_papers:
    min: 0
    max: 200
    required: true
  hot_papers:
    min: 0
    max: 100
    required: true
  indicative_cross_field_score:
    min: 0
    max: 10
    required: true
  percent_docs_cited:
    min: 0
    max: 100
    required: false
  name:
    required: true
    min_length: 2
  esi_field:
    required: true
    min_length: 2

# Output configuration
output:
  reports_folder: "comparison_reports"
  folder_names:
    highly_cited_only: "highly_cited_only"
    incites_researchers: "incites_researchers"

# Dataframe naming configuration
table_naming:
  prefix: "df"

# Statistical Methods Configuration
statistical_methods:
  enabled: true
  z_threshold: 3.0
  methods:
    - "iqr"
    - "zscore"
  append_to_schema: true
  compute_percentiles: true
  fields_to_analyse:
    - "times_cited"
    - "highly_cited_papers" 
    - "hot_papers"
    - "indicative_cross_field_score"
  validation_enabled: true
  outlier_severity_thresholds:
    extreme: 3.0
    high: 2.0
    moderate: 1.5
  performance_logging: true

# Comparison configuration
comparison:
  comparison_columns:
    - "highly_cited_papers"
    - "indicative_cross_field_score"
    - "hot_papers"
    - "times_cited"
  float_tolerance: 0.001
  include_unchanged: true
  include_statistical_comparisons: true

# HTML Generator system    
html_generation:
  enabled: true
  config_path: "html_generator_config.yaml"
  auto_generate: true

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_to_file: true
  log_file_path: "comparison_pipeline.log"
  max_file_size_mb: 10
  backup_count: 5